Second commit

diff --git a/.github/workflows/first-example.yml b/.github/workflows/first-example.yml
--- a/.github/workflows/first-example.yml
+++ b/.github/workflows/first-example.yml
@@ -12,4 +12,4 @@ jobs:
           run: ls
 
         - name: Read File
-          run: cat README.md 
+          run: cat README.md || echo "README.md file is not found"
